src/aztec3/circuits/abis/.test.cpp, src/aztec3/circuits/apps/.test.cpp, src/aztec3/circuits/apps/function_execution_context.hpp, src/aztec3/circuits/apps/test_apps/escrow/.test.cpp, src/aztec3/circuits/apps/test_apps/private_to_private_function_call/.test.cpp, src/aztec3/circuits/kernel/private/.test.cpp, src/aztec3/circuits/recursion/play.test.cpp
=> Specify SRS_PATH when constrcuting Composer in dependent project

src/aztec3/circuits/abis/tx_context.hpp, src/aztec3/constants.hpp
Blocked by https://github.com/AztecProtocol/aztec3-circuits/pull/1 and https://github.com/AztecProtocol/aztec3-circuits/pull/2
=> `TxContext.hash()`

src/aztec3/circuits/kernel/private/.test.cpp
Use () instead of {} in ContractDeploymentData struct initalization to ensure all zeros
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> Use () instead of {} in ContractDeploymentData struct initalization to ensure all zeros

src/aztec3/circuits/mock/mock_kernel_circuit.hpp
The private kernel circuit test was failing with UltraPlonk because we were setting recursive proof elements to be 0, i.e.
$$P_0=(0,0,0,0), \ P_1=(0,0,0,0)$$
where $P_0, P_1$ are recursion elements read from the public inputs of a previous "rollup" proof. These must not be all-zeros, that breaks the MSM operation inside the recursive verifier circuit (breaks only for ultra - separate issue but it _should have_ broken for turbo too!). I have replaced the 0 with random 32-bit numbers (which will eventually be some real recursion elements). 
> **Note**
> ```console
> $ git …
```
=> Fix Private Kernel Circuit Test

src/aztec3/circuits/mock/mock_kernel_circuit.hpp
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> Move unnamed namespace out.

cpp/src/aztec3/circuits/abis/c_bind.test.cpp
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> Add missing frees in abis cbind test

cpp/src/aztec3/circuits/abis/c_bind.test.cpp
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> Cleanup abis cbinds to use std arrays instead of pointers+malloc+free

cpp/src/aztec3/circuits/abis/c_bind.cpp
* memcpy -> std::copy
* use reinterpret casts instead of c-style casts
* use strlen instead of char_traits length
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> Make function selector cbind more C++ like

cpp/src/aztec3/circuits/abis/c_bind.cpp, cpp/src/aztec3/circuits/abis/c_bind.h, cpp/src/aztec3/circuits/abis/c_bind.test.cpp, cpp/src/aztec3/circuits/abis/function_leaf_preimage.hpp, cpp/src/aztec3/circuits/abis/function_signature.hpp, cpp/src/aztec3/circuits/abis/public_circuit_public_inputs.hpp, cpp/src/aztec3/constants.hpp
* Adds a configurable constant num-bytes for function selector
* Adds `FunctionLeafPreimage` struct with a `hash()` function
* Adds Cbind to compute function leaf (takes in a preimage, computes its hash)
* Adds test for `abis__compute_function_leaf` cbind
> **Note**
> ```console
> ```
> ```console
> $ git checkout …
```
=> Function leaf (preimage struct & cbind)

cpp/src/aztec3/circuits/abis/c_bind.cpp, cpp/src/aztec3/circuits/abis/c_bind.h, cpp/src/aztec3/circuits/abis/c_bind.test.cpp, cpp/src/aztec3/constants.hpp
Cbind for `compute_function_tree_root`
**Blocked by: https://github.com/AztecProtocol/barretenberg/pull/247**
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> Cbind for `compute_function_tree_root`

cpp/src/aztec3/circuits/abis/c_bind.cpp, cpp/src/aztec3/circuits/abis/c_bind.h, cpp/src/aztec3/circuits/abis/c_bind.test.cpp, cpp/src/aztec3/constants.hpp
Cbinds for hash_constructor and compute_contract_address
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> feat(cpp): cbinds for hash_constructor and compute_contract_address

cpp/src/aztec3/circuits/abis/barretenberg/aggregation_object.hpp, cpp/src/aztec3/circuits/abis/base_rollup/base_rollup_public_inputs.hpp, cpp/src/aztec3/circuits/abis/c_bind.cpp, ts/src/structs/__snapshots__/base_rollup.test.ts.snap, ts/src/structs/base_rollup.test.ts, ts/src/structs/base_rollup.ts, ts/src/structs/function_data.test.ts, ts/src/structs/kernel.test.ts, ts/src/structs/private_circuit_public_inputs.test.ts, ts/src/structs/shared.ts, ts/src/structs/tx.test.ts, ts/src/structs/tx.ts, ts/src/tests/expectSerialize.ts, ts/src/tests/factories.ts, ts/src/utils/jsUtils.ts, ts/src/wasm/buffer_reader.ts
Typescript and C++ structs for the base rollup public inputs type.
Depends on #76
Related to #41 
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> feat(ts): ABI for base rollup public inputs

cpp/src/aztec3/circuits/abis/c_bind.cpp, cpp/src/aztec3/circuits/abis/c_bind.h, cpp/src/aztec3/circuits/abis/c_bind.test.cpp, cpp/src/aztec3/circuits/abis/private_kernel/new_contract_data.hpp, cpp/src/aztec3/constants.hpp
Blocked by https://github.com/AztecProtocol/aztec3-circuits/pull/82
Once above PR is merged into master, merge master into here (or rebase) and this PR diff should shrink.
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git …
```
=> feat(cpp): cbind for contract leaf

cpp/src/aztec3/circuits/kernel/private/.test.cpp, cpp/src/aztec3/circuits/kernel/private/private_kernel_circuit.cpp, cpp/src/aztec3/circuits/mock/mock_kernel_circuit.hpp
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> Private Kernel Full Test

circuits.code-workspace
Provides out of box C++ experience
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> chore: vscode C++ intellisense workspace

cpp/src/aztec3/circuits/abis/private_kernel/new_contract_data.hpp, cpp/src/aztec3/circuits/abis/private_kernel/private_inputs.hpp, cpp/src/aztec3/circuits/apps/test_apps/basic_contract_deployment/basic_contract_deployment.cpp, cpp/src/aztec3/circuits/apps/test_apps/basic_contract_deployment/basic_contract_deployment.hpp, cpp/src/aztec3/circuits/apps/test_apps/basic_contract_deployment/contract.hpp, cpp/src/aztec3/circuits/apps/test_apps/basic_contract_deployment/init.hpp, cpp/src/aztec3/circuits/kernel/private/.test.cpp, cpp/src/aztec3/circuits/kernel/private/private_kernel_circuit.cpp, cpp/src/aztec3/circuits/kernel/private/private_kernel_circuit.hpp
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> Fix kernel set_public(), add simple private kernel constructor test, kernel comments

ts/src/structs/__snapshots__/base_rollup.test.ts.snap, ts/src/structs/__snapshots__/kernel.test.ts.snap
Fixes ts serialization tests (see https://github.com/AztecProtocol/barretenberg/pull/283).
=> Fix ts serialization tests

circuits.code-workspace, cpp/src/aztec3/circuits/abis/membership_witness.hpp, cpp/src/aztec3/circuits/abis/private_kernel/new_contract_data.hpp, cpp/src/aztec3/circuits/kernel/private/.test.cpp
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> chore: minor rollup tweaks

cpp/scripts/a3-tests, cpp/src/aztec3/circuits/abis/private_kernel/new_contract_data.hpp, cpp/src/aztec3/circuits/abis/rollup/base/base_rollup_public_inputs.hpp, cpp/src/aztec3/circuits/rollup/base/.test.cpp, cpp/src/aztec3/circuits/rollup/base/native_base_rollup_circuit.cpp, ts/src/structs/__snapshots__/base_rollup.test.ts.snap, ts/src/structs/base_rollup.ts, ts/src/tests/factories.ts
- Adding test for the base rollup. 
- Adding a helper function for getting an "empty" set of inputs, that can then be altered afterwards to have meaningful values. 
- Changing public input interface to have 2 fields for the hash (high, low)
> **Note**
> ```console
> ```
> ```console
> $ git checkout <commit_hash>    # Use …
```
=> Adding tests for base rollup + sha256

cpp/dockerfiles/Dockerfile.wasm-linux-clang
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> generate wasm docker img

README.md
Convenience commands added to readme
=> add convenience commands to readme

cpp/src/aztec3/circuits/abis/c_bind.cpp, cpp/src/aztec3/circuits/abis/rollup/root/root_rollup_inputs.hpp
Provides serialisation cbinds for testing c++ etc
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> feat(root): abi serialisation cbinds

cpp/src/aztec3/circuits/abis/c_bind.cpp, cpp/src/aztec3/circuits/abis/c_bind.h, cpp/src/aztec3/circuits/abis/c_bind.test.cpp
cbind for function tree
updates barretenberg with tree compute_tree_native function
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> Compute function tree

cpp/src/aztec3/circuits/rollup/base/utils.cpp, cpp/src/aztec3/circuits/rollup/root/.test.cpp, cpp/src/aztec3/circuits/rollup/root/native_root_rollup_circuit.cpp
- Adds a test that check contracts tree, commitments tree and historic trees are passed correctly along.
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> Extend Root Rollup Test [WIP]

cpp/src/aztec3/circuits/rollup/merge/.test.cpp
Updating the failure regex to make the `EXPECT_DEATH` cases run in CI as locally. Will NOT fix the wasm issues. 
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> Fix `EXPECT_DEATH` cases

cpp/src/aztec3/circuits/abis/rollup/nullifier_leaf_preimage.hpp, cpp/src/aztec3/circuits/rollup/base/utils.cpp
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> fix: update leaf index to uint32

cpp/src/aztec3/circuits/abis/rollup/base/base_rollup_inputs.hpp, cpp/src/aztec3/circuits/abis/rollup/merge/previous_rollup_data.hpp
TS cant serialise base/merge correctly. This fixes the issues!
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> fix serialisation issues with merge/base on ts

cpp/src/aztec3/circuits/abis/rollup/base/base_or_merge_rollup_public_inputs.hpp, cpp/src/aztec3/circuits/rollup/base/native_base_rollup_circuit.cpp, cpp/src/aztec3/circuits/rollup/merge/.test.cpp, cpp/src/aztec3/circuits/rollup/merge/native_merge_rollup_circuit.cpp, cpp/src/aztec3/circuits/rollup/merge/native_merge_rollup_circuit.hpp, cpp/src/aztec3/circuits/rollup/root/.test.cpp, cpp/src/aztec3/circuits/rollup/root/native_root_rollup_circuit.cpp
Fixes #165 by reusing elements from the merge inside the root when possible. 
As the root were not asserting that the right tree build on the left, tests needs to be updated for the full logic to kick in.
> **Note**
> ```console
> ```
> ```console
> $ git checkout <commit_hash>    # Use this if you wish to point to a …
```
=> Align Merge and Root rollup

cpp/bootstrap.sh, cpp/src/aztec3/circuits/abis/private_kernel/previous_kernel_data.hpp, cpp/src/aztec3/circuits/recursion/play.test.cpp, cpp/src/aztec3/circuits/rollup/base/.test.cpp, cpp/src/aztec3/circuits/rollup/base/native_base_rollup_circuit.cpp, cpp/src/aztec3/circuits/rollup/base/nullifier_tree_testing_harness.cpp, cpp/src/aztec3/circuits/rollup/base/nullifier_tree_testing_harness.hpp, cpp/src/aztec3/circuits/rollup/merge/utils.cpp, cpp/src/aztec3/circuits/rollup/root/.test.cpp, cpp/src/aztec3/circuits/rollup/root/native_root_rollup_circuit.cpp, cpp/src/aztec3/utils/types/circuit_types.hpp, cpp/src/aztec3/utils/types/native_types.hpp
This PR updates the bb submodule to point to the latest aztec3 branch. As a result, this PR turns on UltraPlonk for aztec3-circuits. Hence, I needed to fix some Pedersen hash calls to use the correct hash functions that takes care of the composer conditions. 
⚠️ Some of the rollup tests fail locally because the IV table in Pedersen lookup hash isn't initiated correctly while running local tests. This doesn't happen in circleci though. Need to dig deeper into this.
> **Note**
> ```console
> ```
> Alternatively, you can select a particular …
=> Fixes Against Latest BB Submodule

cpp/bootstrap.sh
Improves bootstrap.sh
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> build: dont always clean

cpp/src/aztec3/circuits/kernel/private/.test.cpp, cpp/src/aztec3/circuits/kernel/private/c_bind.cpp, cpp/src/aztec3/circuits/kernel/private/native_private_kernel_circuit.cpp, cpp/src/aztec3/circuits/kernel/private/native_private_kernel_circuit.hpp, cpp/src/aztec3/circuits/rollup/base/.test.cpp, cpp/src/aztec3/circuits/rollup/base/c_bind.cpp, cpp/src/aztec3/circuits/rollup/base/init.hpp, cpp/src/aztec3/circuits/rollup/base/native_base_rollup_circuit.cpp, cpp/src/aztec3/circuits/rollup/base/native_base_rollup_circuit.hpp, cpp/src/aztec3/circuits/rollup/merge/.test.cpp, cpp/src/aztec3/circuits/rollup/merge/init.hpp, cpp/src/aztec3/circuits/rollup/merge/native_merge_rollup_circuit.cpp, cpp/src/aztec3/circuits/rollup/merge/native_merge_rollup_circuit.hpp, cpp/src/aztec3/circuits/rollup/merge/utils.cpp, cpp/src/aztec3/circuits/rollup/root/.test.cpp, cpp/src/aztec3/circuits/rollup/root/c_bind.cpp, cpp/src/aztec3/circuits/rollup/root/init.hpp, cpp/src/aztec3/circuits/rollup/root/native_root_rollup_circuit.cpp, cpp/src/aztec3/circuits/rollup/root/native_root_rollup_circuit.hpp, cpp/src/aztec3/utils/dummy_composer.hpp
Created a native composer and change `assert` to `composer.do_assert()` for base, merge, root rollups.
Usage:
```
DummyComposer composerC = DummyComposer();
native_base_rollup(composer, inputs)
composer.has_failed() -> bool
composer.get_first_failure() -> string (error message)
```
Fixes https://github.com/AztecProtocol/aztec3-circuits/issues/175
> **Note**
> ```console
> ```
> ```console
> $ git pull origin aztec3 …
```
=> tis a good day for we have native composer

cpp/bootstrap.sh
As mentioned in https://github.com/AztecProtocol/aztec3-circuits/issues/236 running tests locally had began to cause issues as some hash methods were using the ultraplonk over turbo methods and vice versa. 
This pr forces makes building use the -USE_TURBO flag, to prevent users encountering this issue.
> **Note**
> ```console
> ```
> ```console
> $ git pull origin aztec3        # This will point to the latest commit in …
```
=> fix: update bootstrap to specify turbo

cpp/src/aztec3/circuits/rollup/merge/.test.cpp, cpp/src/aztec3/circuits/rollup/merge/c_bind.cpp, cpp/src/aztec3/circuits/rollup/merge/c_bind.h
Fixes #52 
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> add cbinds for merge (fix #52)

cpp/dockerfiles/Dockerfile.arm64-linux-gcc, cpp/dockerfiles/Dockerfile.wasm-linux-clang, cpp/dockerfiles/Dockerfile.wasm-linux-clang-assert, cpp/dockerfiles/Dockerfile.x86_64-linux-clang, cpp/dockerfiles/Dockerfile.x86_64-linux-clang-assert, cpp/dockerfiles/Dockerfile.x86_64-linux-gcc
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git push
> ```
=> feat: use turbo in dockerfiles

cpp/src/aztec3/circuits/rollup/base/.test.cpp, cpp/src/aztec3/circuits/rollup/base/native_base_rollup_circuit.cpp, cpp/src/aztec3/circuits/rollup/base/nullifier_tree_testing_harness.cpp, cpp/src/aztec3/circuits/rollup/base/nullifier_tree_testing_harness.hpp, cpp/src/aztec3/circuits/rollup/base/utils.cpp
- Nullifier test tree generation did not have update in place and hence provided incorrect paths.
- Minor fix to the circuit to match the ts verbatim. 
> **Note**
> ```console
> ```
> ```console
> $ cd ..
> $ git add . && git commit -m …
```
=> fix: nullifier tests
